version: "3.8"

services:
  wig_stick:
    build: .
    container_name: wig_stick
    ports:
      - "5000:5000"
    volumes:
      - ./wig_stick:/app
    environment:
      - CUDA_HOME=/usr/local/cuda
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]